### ISSUE TITLE
یه ایراد در سایت های تحریم کننده

### ISSUE THREAD

**Issue by boyitnew** [ircfspace/warpsub#1]
سلام
ممنون از شما و زحماتتون
یه باگی که استفاده از این روش داره اینه که اگر سایتی هم فیلتر باشه و هم تحریم باشیم با ساتفاده از warp هیچ جوره نمیشه دورش زد

اگر خاموشش کنیم که سایته فیلتره باز نمیشه، اگر روشنش کنمی dnsهایی که قبلا برای سایت های تحریمی زده بودیم دیگه کار نمیکنه و warp اجرا میشه 

بهمین دلیل نمیشه اون سایت هارو باز کرد

**Comment by ircfspace** [comment]
سلام
در چنین مواقعی به جای وارپ باید از وارپ‌این‌وارپ استفاده کنین
